import { defineConfig } from 'vitest/config';
import react from '@vitejs/plugin-react-swc';
import path from 'path';

export default defineConfig({
  // @ts-expect-error - Plugin type mismatch between Vite and Vitest's bundled Vite
  plugins: [react()],
  test: {
    globals: true,
    environment: 'jsdom',
    setupFiles: './src/test/setup.ts',
    coverage: {
      provider: 'v8',
      reporter: ['text', 'json', 'html', 'lcov'],
      include: [
        'src/services/**/*.ts',
        'src/utils/**/*.ts',
        'src/lib/**/*.ts',
        'src/store/**/*.ts',
        'src/schemas/manual/**/*.ts',
        'src/features/**/domain/**/*.ts',
        'src/features/**/infrastructure/**/*.ts',
        'src/features/**/shared/utils/**/*.ts',
        'src/features/**/config/**/*.ts',
        'src/features/**/constants.ts',
      ],
      exclude: [
        'node_modules/',
        'src/test/',
        'src/schemas/generated/',
        'src/utils/debug/**',
        'src/utils/consoleCommands.ts',
        'src/utils/googleSheetsApi.ts',
        'src/utils/jsdiff.ts',
        'src/utils/diff.ts',
        'src/services/invoiceExtractor.ts',
        'src/services/realtime/realtime.service.ts',
        'src/lib/indexedDBPersistence.ts',
        'src/lib/queryPersistence.ts',
        'src/services/api/storage.service.ts',
        '**/index.ts',
        'src/**/hooks/**',
        'src/**/contexts/**',
        'src/**/types/**',
        'src/**/testing/**',
        'src/**/components/**',
        'src/**/pages/**',
        'src/**/presentation/**',
        'src/**/templates/**',
        'src/**/atoms/**',
        'src/**/molecules/**',
        'src/**/organisms/**',
        'src/layout/**',
        'src/utils/test-helpers.ts',
        '**/*.test.ts',
        '**/*.spec.ts',
        '**/*.d.ts',
        '**/*.config.*',
        '**/mockData',
        'dist/',
      ],
      thresholds: {
        lines: 5,
        functions: 13,
        branches: 53,
        statements: 5,
      },
    },
  },
  resolve: {
    alias: {
      '@': path.resolve(__dirname, './src'),
      '@components': path.resolve(__dirname, './src/components'),
      '@hooks': path.resolve(__dirname, './src/hooks'),
      '@lib': path.resolve(__dirname, './src/lib'),
      '@pages': path.resolve(__dirname, './src/pages'),
      '@services': path.resolve(__dirname, './src/services'),
      '@store': path.resolve(__dirname, './src/store'),
      '@types': path.resolve(__dirname, './src/types'),
      '@assets': path.resolve(__dirname, './src/assets'),
    },
  },
});
