import {
  CHAT_RUNTIME_INDEXED_DB_NAMES,
  CHAT_RUNTIME_LOCAL_STORAGE_KEYS,
} from '../runtime-persistence';

export const COMPOSER_DRAFT_MESSAGES_STORAGE_KEY =
  CHAT_RUNTIME_LOCAL_STORAGE_KEYS.composerDraftMessages;
export const COMPOSER_DRAFT_ATTACHMENTS_DB_NAME =
  CHAT_RUNTIME_INDEXED_DB_NAMES.composerDrafts;
export const COMPOSER_DRAFT_ATTACHMENTS_DB_VERSION = 1;
export const COMPOSER_DRAFT_ATTACHMENTS_STORE_NAME = 'composer-drafts';
export const COMPOSER_DRAFT_MAX_AGE_MS = 7 * 24 * 60 * 60 * 1000;
export const COMPOSER_DRAFT_ATTACHMENTS_MAX_CHANNEL_BYTES =
  2 * 1024 * 1024 * 1024;
export const COMPOSER_DRAFT_ATTACHMENTS_MAX_TOTAL_BYTES =
  2 * 1024 * 1024 * 1024;
