import { useMemo } from 'react';
import type { ComposerPanelModel } from '../components/ComposerPanel';
import { useChatSidebarControllerContext } from './useChatSidebarControllerContext';

export const useChatComposerModel = () => {
  const {
    message,
    editingMessagePreview,
    messageInputHeight,
    isMessageInputMultiline,
    isSendSuccessGlowVisible,
    isAttachModalOpen,
    pendingComposerAttachments,
    previewComposerImageAttachment,
    isComposerImageExpanded,
    isComposerImageExpandedVisible,
    messageInputRef,
    composerContainerRef,
    attachButtonRef,
    attachModalRef,
    imageInputRef,
    documentInputRef,
    audioInputRef,
    openImageActionsAttachmentId,
    imageActionsMenuPosition,
    composerDocumentPreviewUrl,
    composerDocumentPreviewName,
    isComposerDocumentPreviewVisible,
    imageActionsButtonRef,
    imageActionsMenuRef,
    imageActions,
    setMessage,
    handleKeyPress,
    handleComposerPaste,
    handleSendMessage,
    handleAttachButtonClick,
    handleAttachImageClick,
    handleAttachDocumentClick,
    handleAttachAudioClick,
    handleImageFileChange,
    handleDocumentFileChange,
    handleAudioFileChange,
    handleCancelEditMessage,
    focusEditingTargetMessage,
    openComposerImagePreview,
    closeComposerImagePreview,
    removePendingComposerAttachment,
    queueComposerImage,
    closeComposerDocumentPreview,
    openDocumentAttachmentInPortal,
    handleToggleImageActionsMenu,
  } = useChatSidebarControllerContext();

  return useMemo<ComposerPanelModel>(
    () => ({
      message,
      editingMessagePreview,
      messageInputHeight,
      isMessageInputMultiline,
      isSendSuccessGlowVisible,
      isAttachModalOpen,
      pendingComposerAttachments,
      previewComposerImageAttachment,
      isComposerImageExpanded,
      isComposerImageExpandedVisible,
      messageInputRef,
      composerContainerRef,
      attachButtonRef,
      attachModalRef,
      imageInputRef,
      documentInputRef,
      audioInputRef,
      openImageActionsAttachmentId,
      imageActionsMenuPosition,
      composerDocumentPreviewUrl,
      composerDocumentPreviewName,
      isComposerDocumentPreviewVisible,
      imageActionsButtonRef,
      imageActionsMenuRef,
      imageActions,
      onMessageChange: setMessage,
      onKeyDown: handleKeyPress,
      onPaste: handleComposerPaste,
      onSendMessage: () => {
        void handleSendMessage();
      },
      onAttachButtonClick: handleAttachButtonClick,
      onAttachImageClick: handleAttachImageClick,
      onAttachDocumentClick: handleAttachDocumentClick,
      onAttachAudioClick: handleAttachAudioClick,
      onImageFileChange: handleImageFileChange,
      onDocumentFileChange: handleDocumentFileChange,
      onAudioFileChange: handleAudioFileChange,
      onCancelEditMessage: handleCancelEditMessage,
      onFocusEditingTargetMessage: focusEditingTargetMessage,
      onOpenComposerImagePreview: openComposerImagePreview,
      onCloseComposerImagePreview: closeComposerImagePreview,
      onRemovePendingComposerAttachment: removePendingComposerAttachment,
      onQueueComposerImage: queueComposerImage,
      onCloseComposerDocumentPreview: closeComposerDocumentPreview,
      onOpenDocumentAttachmentInPortal: openDocumentAttachmentInPortal,
      onToggleImageActionsMenu: handleToggleImageActionsMenu,
    }),
    [
      attachButtonRef,
      attachModalRef,
      audioInputRef,
      closeComposerDocumentPreview,
      closeComposerImagePreview,
      composerContainerRef,
      composerDocumentPreviewName,
      composerDocumentPreviewUrl,
      documentInputRef,
      editingMessagePreview,
      focusEditingTargetMessage,
      handleAttachAudioClick,
      handleAttachButtonClick,
      handleAttachDocumentClick,
      handleAttachImageClick,
      handleAudioFileChange,
      handleCancelEditMessage,
      handleComposerPaste,
      handleDocumentFileChange,
      handleImageFileChange,
      handleKeyPress,
      handleSendMessage,
      handleToggleImageActionsMenu,
      imageActions,
      imageActionsButtonRef,
      imageActionsMenuPosition,
      imageActionsMenuRef,
      imageInputRef,
      isAttachModalOpen,
      isComposerDocumentPreviewVisible,
      isComposerImageExpanded,
      isComposerImageExpandedVisible,
      isMessageInputMultiline,
      isSendSuccessGlowVisible,
      message,
      messageInputHeight,
      messageInputRef,
      openComposerImagePreview,
      openDocumentAttachmentInPortal,
      openImageActionsAttachmentId,
      pendingComposerAttachments,
      previewComposerImageAttachment,
      queueComposerImage,
      removePendingComposerAttachment,
      setMessage,
    ]
  );
};
